#!/bin/bash

if [ "$1" == "configure" ]; then
    printf "\n* Post-installing...\n"

    printf "\n* Restarting syslog-ng...\n"
    systemctl restart syslog-ng

    printf "\n* Post-install accomplished.\n"
fi

exit 0
